### ISSUE TITLE
Import, import error

### ISSUE THREAD

**Issue by papahabla** [raycewest/pykeeb#8]
Hello, I'm hoping to make a pyDactyle keyboard and I'm encountering the following import, Import error. Hoping you know of a quick fix. I installed through pip the first time, and then through cloning master, and then running `python setup.py develop`. Getting same error in both cases.

```
09:37 $ python
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykeeb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Home/Code/pyDactyl/pykeeb/pykeeb/__init__.py", line 2, in <module>
    from .keyswitch_mount import Keyswitch_mount
  File "/Volumes/Home/Code/pyDactyl/pykeeb/pykeeb/keyswitch_mount.py", line 4, in <module>
    class Keyswitch_mount:
  File "/Volumes/Home/Code/pyDactyl/pykeeb/pykeeb/keyswitch_mount.py", line 7, in Keyswitch_mount
    alps_keyswitch = Import('/usr/models/matias.stl').color('Gray')
NameError: name 'Import' is not defined
```

**Comment by papahabla** [comment]
Issue seemed to be with this module but was resolved by installing `openpyscad` from git clone of master branch (as stated in this projects README.md).

**Comment by ckaros** [comment]
yea, the openpyscad library is outdated on pip. I have further honed in on the pyDactyl and better replicated Adereth's algorithms in pyKeeb (I commit the new functions in the dev branch of my pykeeb fork. The changes will eventually make it to master after I clean things up). 

Furthermore I have implemented a good way to separate the plate and case that allows attaching them sans screws or glue after printing separately....this make wiring much easier. I will update the pyDactyl repo tonight with the new code after I clean it up.
